name = "printmotive-worker"
main = "index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "PM_KV"
id = "84322bf8490545f18bd2ccd0a985a872"

[[r2_buckets]]
binding = "PM_R2"
bucket_name = "printmotive-assets"
